### ISSUE TITLE
Sonic 3D blast PC port to Psvita  (50$)

### ISSUE THREAD

**Issue by isaquepo** [vita-nuova/bounties#102]
hi , I wanted to open a reward for porting sonic 3d blast from PC to PS Vita!! but first I wanted to know if it is possible to port the gamer.

https://youtu.be/7mWZZ-QShCU

**Comment by MDashK** [comment]
Ouve, eu vou responder-te em Português para ver se tu percebes isto de uma vez por todas.
Os ports para a Vita só são possíveis dentro das seguintes condições:
1) Acesso ao código fonte do jogo: através de várias adaptações do código, torna-se possível portar o jogo para a Vita. Isto, logicamente, tem de ter em conta não só a capacidade do próprio hardware da Vita, como também o uso dos source development kits disponíveis. Ou seja: não consegues correr tudo o que te apetece só porque tens a source. E mesmo que tenhas a source e seja possível a Vita aguentar com o jogo a nivel de hardware, poderá não existir a capacidade a nível de development software para portar o jogo.
2) Portar ALGUNS jogos de Android: isto deve-se ao facto de a Vita ter um processador ARM e de as funções utilizadas pelo mesmo serem semelhantes à maioria dos dispositivos que têm o mesmo tipo de CPU e que usam Android. Daí, ser possível criar uma espécie de port (um wrapper) para fazer correr o jogo na Vita, utilizando uma espécie de redirrecionamento das funções de Android para a Vita.
3) Portar ALGUNS jogos de GameMaker: GameMaker usa uma espécie de "Runner" para executar os jogos e guarda toda a informação do jogo num ficheiro game.win ou semelhante (à excepção de jogos compilados através do modo YYC), e com o uso de ferramentas próprias de descompilação é possível alterar o game.win e portar o jogo para correr no runner da Vita. Com a source code, melhor. Consegue-se compilar directo para a Vita. Mas novamente: isto não implica que todos os jogos onde isto é possível corram correctamente na Vita. Existem limitações não só a nível de hardware com a nível do próprio runner da Vita.

Com tudo isto dito: o jogo que estás a propor corre não só em Windows, como usa DirectX.
Portanto: ou ganhas acesso ao código fonte do jogo e portas a partir daí, e MESMO ASSIM a chance de isso ser possível é INFIMA (porque estamos a falar em adaptar a source de DirectX para a Vita) ou arranjas forma de emular DirectX na Vita para correr o jogo, que novamente, não vou dizer que é impossível, mas deve ser tão possível como viajar da Terra até um buraco negro e chegar lá vivo.
Espero que tenha sido claro e explícito o suficiente.

**Comment by Rinnegatamante** [comment]
Play it with a Genesis emulator.

**Comment by Rinnegatamante** [comment]
You can already play such game on a Genesis emulator.

Il Ven 29 Lug 2022, 01:15 isaquepo ***@***.***> ha scritto:
