### ISSUE TITLE
Update for Bully Port

### ISSUE THREAD

**Issue by EnVic135** [vita-nuova/bounties#104]
Hi. I asked this on Twitter but I think is proper to do it in here. 

As yo can see, I want to know if an update for Bully is possible? The port is already done, but constantly crashes are present in game and is very difficult to pass final mission. 

Is there a way to make an update that (for example) lets the game takes it time to charge maps but with a chance to play between 45 minutes or 1 hour without troubles? I understand if game crashes after that time but at least we'll be able to finish the game and also get 100% if we want. Thanks.

**Comment by Rinnegatamante** [comment]
The game just doesn't properly clear resources it uses. Running out of memory is not a fixable issue.
