### ISSUE TITLE
Boost 2 Android Port

### ISSUE THREAD

**Issue by DvaMishkiLapa** [vita-nuova/bounties#107]
I don't think this project is popular, but maybe someone will be interested. I've been trying to do it myself, but my Python-casual skill is nothing compared to the ton of C++/C dependency errors I get :D.
It's an Android game, pretty old, with an interesting soundtrack and good time-killing potential.

![Screenshot_2022_08_01_15_41_36_21_aa9be33b2f9c23744dc152624d6e008a](https://user-images.githubusercontent.com/18528109/182161170-899d989f-10e4-492a-9103-f1d798188aee.jpg)
**Boost 2.**
Alas, there is no link to the GP. I have no idea where to find it now from good sites, but I do know that the game was free.
It's 3D using G-sensor.
Supports many architectures, including armeabi-v7a.
Has libsanangeles.so in its libraries (if that says anything).
It doesn't have any online features.

**Comment by Rinnegatamante** [comment]
This issue will be closed if in 24hrs there won't be a bounty for it. (And if such eventuality happens, you'll also get permanently blocked from posting in this repository)
