### ISSUE TITLE
Handkerchief game port to Ps Vita [$10]

### ISSUE THREAD

**Issue by IvandersonBordin** [vita-nuova/bounties#108]
Handkerchief is old game for pc(Windows98 or 2000) developed Opus Corp. / Ask, Co., Ltd., published by XSIV Games (Stealth Media Group).
Side-scrolling run'n'gun similar to Metal Slug or Jazz Jackrabbit. Shoot, jump, use weapons and vehicles to combat the enemy army. Single or multiplayer.

![Handkerchief](https://user-images.githubusercontent.com/34588709/182179873-c4dfd6a6-3490-4ac3-8b58-0bf76000ec80.jpg)
![images](https://user-images.githubusercontent.com/34588709/182179882-b7d4a606-7f71-4e9c-bec8-f2946d18d493.png)
![HandkerchiefDemo_PC_16](https://user-images.githubusercontent.com/34588709/182179884-5f28fe92-e6da-4565-8fe7-8a9ce7dee433.gif)

Is it possible to port it to psvita?  It is a very light and very fun game.

**Comment by Rinnegatamante** [comment]
First off: the link you posted is a virus as reported in the description.
Second off: If the game has not an Android build or is not opensource, the game is virtually not portable (It would require a full reverse engine of the game aka something no one is willing to do not even for a very huge bounty).

**Comment by IvandersonBordin** [comment]
Got it, sorry and thanks, I'll close the post.

**Comment by Rinnegatamante** [comment]
If you want to move the money you already dropped in to another target, feel free to edit your first post. Elsewhere, get back the money from Bountysource.
