### ISSUE TITLE
Sonic 3 A.I.R. Port for PS Vita

### ISSUE THREAD

**Issue by ctutts14** [vita-nuova/bounties#109]
I have waited a long time for this, and still, no one has done it.
I am not sure if the android version or the switch version is a better base
so please port it
https://sonic3air.org/

**Comment by Rinnegatamante** [comment]
If in 24 hrs this Issue won't have a bounty attached to it, you'll get permanently blocked from posting on this organization's repositories and the issue will be closed.-

**Comment by thegarlicman123** [comment]
Just ban him already
