### ISSUE TITLE
Starcraft Port PLEASE

### ISSUE THREAD

**Issue by joshworx** [vita-nuova/bounties#11]
It would be so cool to be able to play Starcraft on the go, willing to pay $20 as I'm short on funds, may raise the bounty at a later date.

**Comment by mirh** [comment]
There's this open source engine, but it doesn't really seem the bestest port on the shed
https://github.com/WARGUS/STARGUS
On the other hand, there's this _recompiled_ version for arm
http://repo.openpandora.org/?page=detail&app=package.starcraft

**Comment by Rinnegatamante** [comment]
Gonna close this since no bounty has been provided.
