### ISSUE TITLE
SONIC 3 A.I.R PORTE [50USD$] PC nosso Android

### ISSUE THREAD

**Issue by isaquepo** [vita-nuova/bounties#110]
Would it be possible to port Sonic 3 a.i.r from Sonic 1 and Sonic 2 Android version? Being an RSDK tool?

**Comment by Rinnegatamante** [comment]
If in 24 hrs this Issue won't have a bounty attached to it, you'll get permanently blocked from posting on this organization's repositories and the issue will be closed.-
