### ISSUE TITLE
.ZIM Reader/Wikipedia Reader

### ISSUE THREAD

**Issue by erikhoudini** [vita-nuova/bounties#112]
https://library.kiwix.org/?lang=eng&category=wikipedia

The entirety of wikipedia is only 96ish gb. With a 256gb SD card, that's not unreasonable. 

It's open source:
https://github.com/openzim/

The readers are very lightweight and low on resources.
https://wiki.openzim.org/wiki/Readers

I don't know much in the way of coding but I think this would be really cool addition to the Vita. It would also increase the worth of Vita's that are unable to play games (ie broken). Offline wikipedia with images on a portable device is still very appealing even in 2022, but especially as more people unplug from smart phones and social media.

**Comment by Rinnegatamante** [comment]
You need to open a bounty through Bountysource.
The proposition looks doable (even if, having an offline copy of the whole wikipedia that will likely need to be updated from time to time does sound a bit inconvenient <.<)

**Comment by erikhoudini** [comment]
> You need to open a bounty through Bountysource.

Ah cool. I made an account solely to post this bounty haha!

**Comment by erikhoudini** [comment]
https://app.bountysource.com/issues/110673154-zim-reader-wikipedia-reader

**Comment by erikhoudini** [comment]
$60, I'd pay out with cashapp or Venmo.
