### ISSUE TITLE
Browser for psvita Chrome, opera or anyelse,  [$100-1000]

### ISSUE THREAD

**Issue by mkisamefloweroflotus** [vita-nuova/bounties#115]
Browser for PsVita Chrome, opera or Annelyse, I working in a project but a I need a browser whit the last updates a leas. where I  can navigate whit last plugin of today

**Comment by Dorr8** [comment]
https://vps.gl33ntwine.com/view/61961ecd8c2aa7121aeceb4d/#comment-62bf9cac0da6036dde4c0ddc
http://www.netsurf-browser.org

Netsurf is a good candidate. CSS3, and Javascript have rudimentary and incomplete support, but it is much more likely to be ported than Google Chrome or Opera, as those browsers have a LOT of dependencies, many of those the Vita doesn't have. Meanwhile, Netsurf has much less dependencies, and those dependencies can be fulfilled by the Vita. Also, Netsurf doesn't require a lot of computer power to run. Basically, Netsurf is the most likely candidate for a web browser.
