### ISSUE TITLE
[Android Port] Mass Effect Infiltrator [$45]

### ISSUE THREAD

**Issue by Cyber-Tokyo** [vita-nuova/bounties#122]
Android Port of Mass Effect Infiltrator

**Comment by Cyber-Tokyo** [comment]
Game: [About Game](https://en.m.wikipedia.org/wiki/Mass_Effect_Infiltrator) 


Gameplay: [Gameplay](https://youtu.be/ZDISwkIk_Xk)

**Comment by Cyber-Tokyo** [comment]
Bounty here. 

https://app.bountysource.com/issues/113094798-android-port-mass-effect-infiltrator

**Comment by Andiweli** [comment]
I'll add 10 bucks too here... 👍🏻

**Comment by mmayfield** [comment]
Added $25
