### ISSUE TITLE
Marathon 1994 Port

### ISSUE THREAD

**Issue by Mikethemlgdeck** [vita-nuova/bounties#128]
https://www.youtube.com/watch?v=zNDARJ-eAqU&t=140s

and here is where you can download the game, from what i've heard this has a psp port, but not a vita one, if anyone is interested in making this, it'd be great if you do, from what i've heard this has gamepad support, so that should make things easier.

**Comment by Rinnegatamante** [comment]
If a bounty won't be started in the next 12 hours this issue will get closed and you'll get permanently blocked from this organizatrion due to off-topic.
