### ISSUE TITLE
Hard Time (2013) Android port [10$]

### ISSUE THREAD

**Issue by Warp1nx** [vita-nuova/bounties#129]
![unnamed](https://user-images.githubusercontent.com/85808172/204196729-7be6b92c-1180-4f5f-b1f2-f0dc020cee0f.png)

![unnamed](https://user-images.githubusercontent.com/85808172/204196782-247af795-4fad-42ac-b131-73a070ae5030.png)

This game would be cool! Throwing a small bounty out there :)

**Comment by Rinnegatamante** [comment]
If a bounty won't be started in the next 12 hours this issue will get closed and you'll get permanently blocked from this organizatrion due to off-topic.
