### ISSUE TITLE
Fixing speed and flashing textures for smash remix on deadulus 64

### ISSUE THREAD

**Issue by ChrisDG776** [vita-nuova/bounties#13]
Fixing dynarec and stuff so it doesn't crash when used or flashing textures on certain stages.

**Comment by ChrisDG776** [comment]
Of course its just a homebrew game and it only runs at 20 to 27 frames for most of the time. And i know probably that Rin doesn't care about this and even if he did he'd probably say emulate it on something else. Also if this can be fixed i would be very happy.

**Comment by Rinnegatamante** [comment]
This is not a bounty (?)

**Comment by ChrisDG776** [comment]
it is its to fix speed and textures.
