### ISSUE TITLE
[Android] RCT Classic + OpenRCT2 + RCT3 Mobile ($100)

### ISSUE THREAD

**Issue by sevvyb** [vita-nuova/bounties#135]
I'm new here, I know I need to signup and create a bounty, but I'm not ready yet. I'll probably create the bounty in a few days after reading some replies first

I want to make a request and see what people think, if this is possible or not... I'm not sure if other people contribute towards the bounty or how that works?? I don't want to create 3 separate bounties, but hopefully other people can pitch in lol... I am willing to offer a bounty for 3 separate games + DLC add-ons, $25 each for a total of $100 if all 3 play smoothly and include all extra DLC add-ons 

________________________________________________________________________________________________________________

🥇  **BOUNTY 1 = I will offer $25 if somebody can port RCT Classic (Android) to PSVita**

[RCT Classic](https://play.google.com/store/apps/details?id=com.atari.mobile.rctclassic&hl=en_US&gl=US) is available for Mobile/Android and seems like it could easily run on Vita... just to be clear: **RCT Classic** includes both RCT1 Deluxe and RCT2 combined into one app (not separate)

[DLC:](https://store.steampowered.com/app/683900/RollerCoaster_Tycoon_Classic/) theres some little DLC add-ons which go with it (they should be included automatically)

**CONTROL SCHEME:** the Android/Mobile version is entirely built around touch-screen controls (which are not great), while the original PC version is based entirely around mouse/keyboard. the PC version includes customization options for reconfiguring the controls, so my hope is to utilize both controls and touch-screen on Vita. The analog sticks should function as mouse to scroll the camera, and ideally using the buttons or triggers for left-click, right-click, etc.

________________________________________________________________________________________________________________

🥇  **PART 2 = I'll offer an _additional_ $25 ($50 total) to include OpenRCT2 along with RCT Classic (since they go together)**

[OpenRCT2.org](OpenRCT2.org) is an Open-Source fan-made project which combines with RCT Classic (like a major upgrade) to improve many new features... I realize OpenRCT2 is more for PC but they do have an Android port, it is open-source and the OpenRCT devs work directly with RCTclassic-engine as they are identical, so maybe that could be useful?? OpenRCT2 is all about customization features, so the more of those customization features you can add into the game the better the experience will be 💯 

The OpenRCT devs might be willing to help if somebody wants to contact them (I would do it myself but I'm not a coder lol) they are completely open-source though. Like I said, the big problem with the Android/Mobile ports is the lack of controls, but if Vita can utilize both touch-screen and proper controls, it might actually be perfect!!

Theres also built-in save/transfer tool for PC to Mobile (its an automatic feature) its always been very easy to transfer save files from one device to another, and save files are compatible between the different games too! Plus theres tons of mods and custom "user-generated content" available for the game (at least on PC not sure if all UGC is 100% compatible with Android)

________________________________________________________________________________________________________________

🥇 **PART 3 = I'll offer another $25 for RCT3 and if it all runs smooth _including the extra stuff_, maybe I'll throw in another$25 to make it total of $100 for everything!!**

HOWEVER performance must be visually smooth and only if enjoyable during construction of rides AND while riding First Person perspective at high-speeds...... RCT3 probably will require a lot more work though, as it is a buggy game so, that's why I'm willing to offer the extra $25 if its actually decent performance (and includes most of the extras)

[RCT3 Mobile](https://apps.apple.com/us/app/rollercoaster-tycoon-3/id1008692660) is not really important though, cuz its a buggy game.... I mainly just want RCTclassic since I believe the Vita should be able to easily handle RCTclassic, and I'm not paying a bounty for poor performance... actually performance might not be the issue tho (at least not for RCTclassic), its probably more about the controls (needs analog support)

[DLC:](https://store.steampowered.com/app/1368820/RollerCoaster_Tycoon_3_Complete_Edition/) technically theres 2 expansion add-ons for RCT3 but, sadly I don't think they fully ported over to Mobile since they were always kinda buggy, so that will be the icing on the cake if its possible to include the water park add-on for RCT3 cause that really would complete the set!!

NOTICE: Please do NOT waste time with any other RCT games... I do NOT want RCT4 or Deluxe or Gold whatever... I do NOT want RCT Touch or RCT Puzzle... they are pay-to-win and those all _suck!!!_ so please do not bother with those, just ignore RCT4 and ignore RCT Touch ... maybe Parkitect might be popular, but I never got into that one and its not actually part of the RCT series ... my point is, I am _not_ offering any bounty for any other games 

**I only want the original RCT trilogy! Thanks**

**Comment by Rinnegatamante** [comment]
That's now how bounties work. You go on Bountysource and actually start a bounty dropping real money on it giving the issue here on github as reference. Also one bounty per issue.

Btw OpenRCT2 has a prototype build since years but I/O speed is a huge constraint.
