### ISSUE TITLE
[Android Port] Call of Duty: Black Ops – Zombies

### ISSUE THREAD

**Issue by Tentha** [vita-nuova/bounties#138]
I'm a big fan of cod zombies in general and love to play this game now and then.

since it's labled as "Candidate" on [https://android.rinnegatamante.it/](https://android.rinnegatamante.it/) I thought I'd put a bounty on it.

if possible it would be great to have controller support for thi game so you'll be able to use the vita controlls instead of the touch controlls.

Here is the link to the game

Name: Call of Duty:Black Ops Zombies
Version: 1.0.8
[Google Play Link:](https://play.google.com/store/apps/details?id=com.activision.boz&hl=en&gl=US)

the game has been taken offline so you can't get it from the store but I can provide the game if needed since I still got it on my phone installed and stored as a APK file.

If there anything else I can help with I would love to provide it.

**Comment by Rinnegatamante** [comment]
Writing [$50] on the side of the message doesn't turn it a bounty. Either you attach a bounty or i'm going to close this and block you from this repository.

**Comment by Tentha** [comment]
> Writing [$50] on the side of the message doesn't turn it a bounty. Either you attach a bounty or i'm going to close this and block you from this repository.

My apologies but I don't know how to turn it into a bounty. Do I turn it into a bounty on github or on another site?

**Comment by Rinnegatamante** [comment]
https://app.bountysource.com/?order=created_at&direction=desc
