### ISSUE TITLE
Hyper Light Drifter port

### ISSUE THREAD

**Issue by samuelschoon** [vita-nuova/bounties#139]
Didn't create a bounty yet cause I'm not sure if it's possible, but it would be super sweet to get the android version of HLD on the ps vita. It would look amazing on an oled screen. It was actually originally supposed to come out for ps vita, but was scrapped in the end. Would be cool to see it finally come to fruition!

**Comment by Rinnegatamante** [comment]
Hyper Light Drifter has no Android version.
