### ISSUE TITLE
[Android Port] The World Ends With You [$50]

### ISSUE THREAD

**Issue by hifumidere** [vita-nuova/bounties#140]
The game already has touch controls and I think it would be a good fit for the vita 
![unnamed](https://user-images.githubusercontent.com/45135121/214463357-643eacc4-2105-443f-a78a-872cfc6fa635.png)

**Comment by dotamann** [comment]
Hi! I also believe that TWEWY is portable to vita and also a great addition to vita's library on top of it, so I'm contributing to this bounty as well :)

**Comment by Arka161** [comment]
It is not feasible to port this using the SO Loader method, as the game is made using Unity. 
![image](https://user-images.githubusercontent.com/20723780/228918787-ffacac19-81f4-4919-aa26-edfe8b058d2e.png)

**Comment by dotamann** [comment]
> It is not feasible to port this using the SO Loader method, as the game is made using Unity. 

Man that sucks. I thought since its an old android game, it might had a similar porting process to World of Goo(another old, 2d android game). Anyways, is there another way to port it? I'd really like to see this game working on Vita.

**Comment by v-atamanenko** [comment]
Yes. There are people who do Unity ports. @hatoving for example

**Comment by dotamann** [comment]
> Yes. There are people who do Unity ports. @hatoving for example

Great! I hope someone ports it one day.  Its a pretty good game and playing it on a phone kinda sucks

**Comment by Arka161** [comment]
Thanks so much for the response. If you don't mind me asking, what is the reason a Unity to Vita port is considered hard? Is there a lot of technical challenges compared to the SO Loader method?

**Comment by dotamann** [comment]
> Thanks so much for the response. If you don't mind me asking, what is the reason a Unity to Vita port is considered hard? Is there a lot of technical challenges compared to the SO Loader method?

Gee, I wish I knew about these stuff. Ask Rinne. Im sure he can give you an answer to that. The guy is a genius when it comes to porting games on the Vita system

**Comment by hatoving** [comment]
hi, since the world end with you's android port is practically an old ass one, it means it's a lot more outdated, meaning that there's a chance that i can port it (it will take a lot of time though since games like this use a lot of android api shiz...)

**Comment by dotamann** [comment]
> hi, since the world end with you's android port is practically an old ass one, it means it's a lot more outdated, meaning that there's a chance that i can port it (it will take a lot of time though since games like this use a lot of android api shiz...)

Hello! Yes, TWEWY solo remix has been released on android devices in 2014 so its safe to say that we are talking about an old port. That would be very nice if you give it a try! Its okay, you can take your time with it. I just hope one day to see it running on a vita.

**Comment by hatoving** [comment]
It's done, here ya go: https://github.com/hatoving/twewy_vita
UPDATE: Made it private for now due to fuHEN. Gonna make it public as soon as it gets published on there

**Comment by Rinnegatamante** [comment]
Closing so that bounty can be claimed.

**Comment by dotamann** [comment]
> It's done, here ya go: https://github.com/hatoving/twewy_vita UPDATE: Made it private for now due to fuHEN. Gonna make it public as soon as it gets published on there

Much appreciated my friend! You have made one hell of a port. I love it! TWEWY Solo Remix has finally found a new home. Vita community never cease to amaze me!
