### ISSUE TITLE
[Android Port] Call of Duty Black Ops: Zombies [$20]

### ISSUE THREAD

**Issue by plxst** [vita-nuova/bounties#144]
Would be sick on the vita

**Comment by Rinnegatamante** [comment]
Woulb de sick if you'd open a bounty rather than just opening an Issue to beg.

**Comment by plxst** [comment]
New to this platform I don't know how to open a bounty

**Comment by Brandonmccoub2** [comment]
yeah that would be amazing! Bearing in mind that you can't play it anymore on modern versions of android, it doesn't work on Android 10 upwards I believe. :)

**Comment by Brandon98SE** [comment]
Can this be re-opened?
