### ISSUE TITLE
[Android Port] Call of Duty: Black Ops - Zombies Mobile (no money incentive for now)

### ISSUE THREAD

**Issue by nahCyzar0520** [vita-nuova/bounties#156]
(**Not to be confused with Call of Duty: Mobile**)

This is an old 2011 android game published by Activision that was on the Google play store (no longer up there). This game is the hoard mode (Zombies) from Call of Duty: Black Ops but put into a monetized android form. You can play 3 maps from Call of Duty: Black Ops which is Kino, Ascension, and Call of the Dead. Along with that there is a hidden way to unlock the game mode Dead Ops Arcade (hint: there are 4 hidden coins in the menus). I do have instructions to get an APK through a sketchy site:
![Screenshot_20230326-140229-085](https://user-images.githubusercontent.com/92120273/227796780-441af8e1-ab2b-47a0-919b-d5298b18fb57.png)

Name: Call of Duty: Black Ops – Zombies
Online features: Multiplayer, Cod Points
Version: Not available currently on the Google play store.
Has ARMv7 build: Not known by commenter
GLES version: Not known by commenter

**Comment by Rinnegatamante** [comment]
"(no money incentive for now)" Then don't open an Issue here.
