### ISSUE TITLE
TES IV Oblivion port for the Vita?

### ISSUE THREAD

**Issue by EliMCGamerGuy** [vita-nuova/bounties#16]
this is less of a bounty, but more of a suggestion.

It turns out there was a scrapped Oblivion spinoff game for the PSP, I downloaded it and stuck it into my Adrenaline, and it looked fine for Oblivion, ran fine, too. my question is: would a Oblivion port for the Vita be possible?

**Comment by Nacho-exe** [comment]
Would love to see this happen!!

**Comment by EliMCGamerGuy** [comment]
[Here's a video I found of the PSP developer demo in action](https://www.youtube.com/watch?v=7uHJ7RWLgCM)

**Comment by mirh** [comment]
https://gitlab.com/OpenMW/openmw
This is what you are aiming for if any

**Comment by Rinnegatamante** [comment]
Oblivion is too demanding for Vita and closed source.

**Comment by EliMCGamerGuy** [comment]
darn, I guess that is true.
