### ISSUE TITLE
Arm64 on ps vita? [$5]

### ISSUE THREAD

**Issue by Sal-gamer** [vita-nuova/bounties#178]
Good morning, there is a theflow project to use the psp's cpu mips outside of psp mode on ps vita, for games and modulators, the name of this project is "VitaMips
 This is a homebrew example that demonstrates how to integrate the MIPS processor into homebrew without the need for a kernel plugin.  This feature is beneficial for PS1, PS2 and N64 emulators." link: https://github.com/TheOfficialFloW/VitaMips
  The PS Vita has the PSP's CPU and GPU inside it, The Vita's CPU has 4 ARM Cortex-A9 cores + 4 PowerVR GPU cores + 8 cores for video/audio codec processing

 Sony decided to include PSP CPU (mips) + GE GPU within the Vita hardware
 source: https://github.com/vita-nuova/bounties/issues/5

 With everything I want to get to a place saying this, would it be possible for the arm 64 cpu instructions to be emulated in software that divides 32 bits for the vita cpu and 32 bits for the mips cpu, thus managing to process 64 bits of instruction at the same time?  the mips cpu has many open source emulators that transform mips into arm but I mean doing the opposite, trying to convert the arm instruction to the equivalent of mips, and while the two cpus work I believe the GE gpu could work together with software to manage the emulating each cpu and processing the data input and output of each cpu did or will do and unite the information as one or share it effectively, using gpu ge as a processing unit, of course this would use a lot of memory, so I suggest an implementation of a new codec, if possible, implement the avif image and av1 video codec with a plugin or software so you can use much less memory without loss of images or video, with all that said I want to get to the point where I would like to use this to If it's possible to port 64-bit Android ports arm64, I know it still has compatibility with the Vita GPU using OpenGL 2.0, but with time the game's graphical API can be corrected to work in OpenGL 2.0 with a lot of effort!

**Comment by jejejejeje12** [comment]
Sleep dreaming because it's very difficult to make a Play Station 2 emulator if you can but they would have to be a god programming or that several developers help you in making it possible but never only in dreams that's why I make fun of you with a song link       https://www.youtube.com/watch?v=C41kNV94zNE     jejejejejejej

**Comment by Sal-gamer** [comment]
it doesn't hurt to dream

**Comment by Sal-gamer** [comment]
😟
