### ISSUE TITLE
PICO-8 emulator for PS VITA [$41 awarded]

### ISSUE THREAD

**Issue by SolomonSquek** [vita-nuova/bounties#18]
As the title says, a PICO-8 emulator for the ps vita would really be a nice thing to see. There are some Pico-8 open source emulators out there, the most promising one being tac08 ( https://github.com/0xcafed00d/tac08 ), which already works on other platforms like the rg350 ( https://0xcafed00d.itch.io/tac08-rg350 ) 

here are some other sources which might be useful
https://github.com/Jakz/retro8
https://github.com/picolove/picolove (this one is a pico-8 implementation in löve)

So it would be wonderful if someone could port one of these on psvita

**Comment by jtothebell** [comment]
I've ported my Pico 8 emulator to Vita. I still need to do a bit of clean up and post a release with the latest changes and added platforms, but you can get the latest build from the build artifacts (https://github.com/jtothebell/fake-08/actions/runs/628037072 as of now). Its not 100% perfect, but none of the Pico 8 emulators are. I think it should be about on par with tac08, and better compatibility than picolove. I haven't tried retro8, so I'm not sure about that.

**Comment by SolomonSquek** [comment]
Hey, that's great! I've tried it with a bunch of games and they run almost flawlessly, that's amazing!
It still need some polishness but it seems pretty much ready
But I wanted to ask, is there a way to choose between the d-pad and the analog stick, or could this be implemented?
Anyway thanks a lot!

**Comment by jtothebell** [comment]
I'm sure I could add support for the analog stick as well as the d pad. I think the easiest thing would be to accept input from both instead of adding a toggle between them. I'll add that to my list. Do you have any other specific polish suggestions? The couple other vita specific things I still plan to do are update the initial screen with platform specific instructions (ie replace "sdmc:/" with "ux0:/", update button names). I've had a couple people request a different front end (https://github.com/jtothebell/fake-08/issues/30) but that's probably a platform specific thing that I'm not going to get to in the short term at least.

**Comment by SolomonSquek** [comment]
The screen resizing with R doesn't seem to work on my ps tv, but other than that yeah the main thing is game-compatibility, one or two of them didn't start at all and another one (Foreverred) crashed the emulator
I'm still pretty impressed by your work, the games that work, work flawlessly and the audio has no issues, great job!
Anyway I think too that it should get a nicer front-end (specifically, the starting background black image) to make it more inviting, but I understand it has a low priority so no problem, keep going!

**Comment by jtothebell** [comment]
If you check the latest build (https://github.com/jtothebell/fake-08/actions/runs/644826549 as of now) the stretching should be fixed, and Foreverred should run. There is still a problem with some glitched graphics on the title screen, but I was able to play through several screens. I also added a friendlier background image and support for analog stick controls.

**Comment by SolomonSquek** [comment]
That's awesome, tried it with multiple games and all worked just fine
I think you should take the bounty, but since I'm new to bountysource I don't know how all this works, if you do let me know
You should also post about it on https://www.reddit.com/r/vitahacks/ , I'm sure a lot of people down there will love to see this emulator

**Comment by Rinnegatamante** [comment]
If the bounty can be considered fullfilled, i'm gonna close this issue so that the author can claim it. Let me know.

**Comment by SolomonSquek** [comment]
Yes Rinne, thanks

**Comment by jtothebell** [comment]
Just updated docs, created a release (https://github.com/jtothebell/fake-08/releases/tag/v0.0.2.3), and posted on r/vitahacks (https://www.reddit.com/r/vitahacks/comments/m3um3j/release_fake08_a_homebrew_pico_8_emulator/)

**Comment by Rinnegatamante** [comment]
@jtothebell Closed the issue, feel free to claim the bounty.

**Comment by jtothebell** [comment]
@Rinnegatamante how do updates get posted VitaDB? Someone else added FAKE-08 to VitaDB a couple weeks ago, but there have been a couple updates since the version that is live and it would be great if people could easily get the latest version from there.

**Comment by Rinnegatamante** [comment]
You can contact me whenever you want me to add a new version on it. (You can find me on Discord too: https://discord.gg/PyCaBx9
