### ISSUE TITLE
Minigore 2: Zombies | PS Vita Port | $100

### ISSUE THREAD

**Issue by qlGGlp** [vita-nuova/bounties#20]
This is my absolute favorite game of all time on Android, you can play it over, over and over again. It's just endless and pure fun with great humor! I'm offering $100 or more if that would make someone start working on it.

X

**Comment by Rinnegatamante** [comment]
Therre's no bounty set on this issue and you're linking a pirated apk download.

**Comment by qlGGlp** [comment]
I'm very sorry for the fuss Rinne. I'm not using PayPal anymore so there's no way for me to offer the money.
