### ISSUE TITLE
GemRB port for PSVITA [$50 awarded]

### ISSUE THREAD

**Issue by Rinnegatamante** [vita-nuova/bounties#3]
As the title implies, this bounty is for a fully working port of GemRB, popular recreation of Bioware's Infinity Engine.

A port of GemRB would allow to play Baldur's Gate, Icewind Dale and Planescape: Torment on the go on PSVITA.

**Comment by lynxlynxlynx** [comment]
Hey, just saw this today and while it doesn't look to be going well, if anything does happen, do keep us (=GemRB team) in the loop. We like to keep the ports inside our tree, so they remain maintained.

Considering there's already an sdl port for vita, it likely compiles out of the box. In the best case scenario one would just need to hardwire some of the keys/controls, so it'd be more pleasantly playable.

**Comment by dagdha2002** [comment]
Hello. I´ve been trying to let a reward via Bountysource to this project without success. If you are still working in that port, I can collaborate with $40. Thanks for your work.

**Comment by Rinnegatamante** [comment]
Bountysource is having a lot of disruption troubles lately. When things will get sorted out on their end, you'll be able to place a bounty here: https://www.bountysource.com/issues/77901879-gemrb-port-for-psvita?utm_campaign=plugin&utm_content=tracker%2F144821204&utm_medium=issues&utm_source=github

**Comment by lynxlynxlynx** [comment]
Btw, @Northfear just finished the port. I don't know if he published the build anywhere yet, but if he did, he deserves the bounty.

**Comment by Northfear** [comment]
@dagdha2002 I saw you asking my contact info on Bountysource. You can drop me a message on Discord if you're still having any problems or bugs to report (Northfear#8713). Save games with reproducible bugs or core dumps are welcome.
