### ISSUE TITLE
NBA 2K20 Android Port for PS Vita

### ISSUE THREAD

**Issue by AnGeloo619** [vita-nuova/bounties#33]
The game port is a real opportunity to give the ps vita the games it has always deserved. 
however I notice that no one seemed to be interested in porting a reference sports game like 2K on Android. 
It would be really interesting to see if possible what a basketball game on ps vita could give.

https://play.google.com/store/apps/details?id=com.t2ksports.nba2k20and

**Comment by twomigs** [comment]
I follow the same sentiment. Why was this closed? Is there a bounty page for this?

**Comment by Rinnegatamante** [comment]
No which is why it got closed.

**Comment by twomigs** [comment]
Thank you for responding rinnegatamante. Im a huge fan of you work. I did notice that nba 2k20 was not on list of possible android games to be ported to the vita thats why I googled it and saw this. Let me try to hype it up on reddit. It is possible to get it ported right?
