### ISSUE TITLE
STREETS OF RAGE REMAKE BENNUGD [50$] [$100 awarded]

### ISSUE THREAD

**Issue by suckrpunch** [vita-nuova/bounties#36]
I would love to see a streets of rage remake port on the PSVITA BENNUGD is an opensource game engine a fork of fenix.
Some links that may help:
https://gbatemp.net/threads/streets-of-rage-remake-bennugd-monolithic-could-it-be-done.506090/

http://forum.bennugd.org/index.php/topic,715.0.html

![new_me10](https://user-images.githubusercontent.com/81054350/111888459-033c6700-89dd-11eb-917d-f0d6e1c672f4.png)

![download](https://user-images.githubusercontent.com/81054350/111888444-d5572280-89dc-11eb-8876-dd87027133d2.jpg)

**Comment by Brandonheat8** [comment]
Can I add another $50 to this?

**Comment by Brandonheat8** [comment]
Added $50

**Comment by panreyes** [comment]
Hi! 

I am not interested in the bounty and I have no time to help you more than these comments, but here's what you need to know to port BennuGD, the game engine (not just the game):
- BennuGD is a game engine that compiles a bytecode that can be played with another compiled interpreter. It's easier to say that it works like Java: You have the JavaVM and the JAR files, and the JAR files run in that VM. In BennuGD, you have BGDI (BennuGD Interpreter) and DCB/DAT files, that are interpreted by the BGDI.
- Original BennuGD can't be compiled easily to new platforms: you would need to edit the makefile by hand. You could solve this by using BennuGD-monolithic ( https://gitlab.com/josebagar/bennugd-monolithic ), which has CMake scripts to make the compilation it a lot easier.
- BennuGD requires SDL1.2, but BennuGD-monolithic uses SDL2. AFAIK, that will also make the VITA port easier :)

After porting the game engine, you can easily play most BennuGD games with just putting the files in the right place. You could also play those open source games I created a long time ago:
http://www.pixjuegos.com

But, maybe, it would even be more interesting to learn how to create BennuGD games. BennuGD uses "DIV Games Studio" code, which is quite easy to understand for beginners. There are some simple games codes here:
https://code.google.com/archive/p/apagame4be/downloads?page=1

That would be it, #GLHF! 😊

**Comment by isage** [comment]
https://github.com/isage/sorr-vita/releases/tag/v1.0

**Comment by Rinnegatamante** [comment]
Closing the issue so the bounty can be collected.

**Comment by isage** [comment]
Sadly, bounty can't be collected. Bountysource is effectively dead. You can't register (it doesn't send verification mails), and payouts take months in a best case (and you need to jump through hoops by writing emails to current CEO).

**Comment by panreyes** [comment]
Hi Ivanov.

Congrats on the port! 👏

About the FPS drop, it may help if you clear up SDL2 events after every
frame.

Please let me know if it helps :)
[Edited: Removed email reply garbage.]

**Comment by isage** [comment]
@panreyes thanks. Ignoring mouse/touch/key/wm sdl events seems to have helped.
