### ISSUE TITLE
Light Cycle 3D (1.05) by Wishbone

### ISSUE THREAD

**Issue by a7xpadd3r** [vita-nuova/bounties#39]
Hello everyone, I was wondering if it is possible to port this version of the game, I know that the PSP versions exists, but I'm asking about this specific one 1.05

Wishbone page is gone, you can get the game from [here](http://www.caiman.us/scripts/fw/f389.html).

![lc3d1](https://user-images.githubusercontent.com/81482233/112728016-ee436480-8f03-11eb-8cae-6f266f5a59f7.png)
![lc3d2](https://user-images.githubusercontent.com/81482233/112728018-f00d2800-8f03-11eb-8778-c3b8934370cc.png)
![lc3d3](https://user-images.githubusercontent.com/81482233/112728019-f0a5be80-8f03-11eb-8c5d-986f661abd3a.png)
![lc3d4](https://user-images.githubusercontent.com/81482233/112728021-f13e5500-8f03-11eb-8a11-037c0b7cb431.png)
![lc3d5](https://user-images.githubusercontent.com/81482233/112728025-f3a0af00-8f03-11eb-84cc-6043b034c214.png)
![lc3d6](https://user-images.githubusercontent.com/81482233/112728028-f4d1dc00-8f03-11eb-9fe2-6d1ce897548d.png)
![lc3d7](https://user-images.githubusercontent.com/81482233/112728029-f56a7280-8f03-11eb-9deb-8926aef5d842.png)

**Comment by Rinnegatamante** [comment]
Closed source.
