### ISSUE TITLE
Turbo F.A.S.T/Racing League 

### ISSUE THREAD

**Issue by thee3rdplayer** [vita-nuova/bounties#40]
A mobile racing/sim game based on the movie 'Turbo'. This game is now off the Online stores like Play & App Store, which I guess gives us more chance of getting it.

*Download link for Android version* 
https://turbo-racing-league.en.uptodown.com/android

**Comment by Rinnegatamante** [comment]
Stop pushing stuffs there without opening bounties. This is not a free market.

**Comment by thee3rdplayer** [comment]
Noted.
