### ISSUE TITLE
ZGloom Port for PS Vita (Gloom, Gloom Deluxe, Zombie Massacre) [$30 awarded]

### ISSUE THREAD

**Issue by Andiweli** [vita-nuova/bounties#43]
**Gloom** and it's later updated version **Gloom Deluxe** were some decent Doom clones back in the 90s for Commodore Amiga computers. You needed a pretty powerful Amiga back then. I can remember even my A1200 with 68040 accellerator and additional Fast-RAM had problems playing it fullscreen (320x256 pixels) with floor/ceilings activated :)

![Title and gameplay](http://hol.abime.net/pic_full/dbs/2701-2800/2741_dbs1.png)

The source code and game files of the game have been made public a few years ago by the developers and there are also Linux and Windows ports already available. Those are compatible not only with the first [Gloom](https://hol.abime.net/2739) game (chunky graphics and no floor/ceiling textures) - the ports are also compatible with [Gloom Deluxe](https://hol.abime.net/2741), [Gloom 3](https://hol.abime.net/1799), [Zombie Massacre](https://hol.abime.net/4574) and [some mods](http://eab.abime.net/showthread.php?p=993127).

In addition to built-in controller support the available port already has a save function, level select, ingame music and you can set custom resolutions.

You can take a look at the Linux/Windows port below.

[ZGloom Teaser Video](https://www.youtube.com/watch?v=Hj5rdHoyy-Y&list=FL9Q_hZwZqg7QS1HLIPrNidg&index=1&ab_channel=TwoOwls)
[Gameplay Video on an Amiga](https://www.youtube.com/watch?v=T8r8s79g7wI&ab_channel=Spillhistorie.no)

The source files are available [here (original game)](https://github.com/earok/GloomAmiga) and [here (ZGloom port)](https://github.com/Swizpig/ZGloom).

**Comment by JetStreamSham** [comment]
I started porting ZGloom to the vita. The fps is a really low but it is playable with multithreading turned on. I may come back to this later, if someone else wants to continue working on this feel free. 


https://github.com/JetStreamSham/ZGloom-vita

**Comment by Andiweli** [comment]
Uhhhh great fantastic! With multithreaded renderer I find it quite playable 👍🏻
Can the backside touchpad be disabled somehow?

**Comment by JetStreamSham** [comment]
The back touchpad is disabled for me, is it shooting for you? 
What plugins do you have running?

**Comment by Andiweli** [comment]
It just does rotate left right if I swipe left or right on the backside...

Plugins in my ur0/tai...

fd_fix
ioplus
itls
kubridge
nonpdrm
nopsmdrm
ref00d
repatch
storagemgr

**Comment by Andiweli** [comment]
@JetStreamSham I filed some issues. With 1.0.1 right controller + keyconfig + trigger isn't working anymore.

**Comment by Rinnegatamante** [comment]
@JetStreamSham Is the release considered an official release or a debug/test version?

**Comment by JetStreamSham** [comment]
test version
I'm going to fix these 2 issues:
[https://github.com/JetStreamSham/ZGloom-vita/issues/4](https://github.com/JetStreamSham/ZGloom-vita/issues/4)
[https://github.com/JetStreamSham/ZGloom-vita/issues/2](https://github.com/JetStreamSham/ZGloom-vita/issues/2)  and then it will be the official release unless there's something else that really bad that needs fixing.

**Comment by Andiweli** [comment]
> test version
> 
> I'm going to fix these 2 issues:
> 
> [https://github.com/JetStreamSham/ZGloom-vita/issues/4](https://github.com/JetStreamSham/ZGloom-vita/issues/4)
> 
> [https://github.com/JetStreamSham/ZGloom-vita/issues/2](https://github.com/JetStreamSham/ZGloom-vita/issues/2)  and then it will be the official release unless there's something else that really bad that needs fixing.

I support that 👍🏻
If it's ok for you I would extend your port when finished with support for extra Vita apps for all the other clones of the game.

**Comment by JetStreamSham** [comment]
Sure, go for it.
I'll come back periodically to add features and fixes so if  there's features or fixes you want for this port, make an issue with the label feature.

**Comment by JetStreamSham** [comment]
I've fixed those two issues :
[https://github.com/JetStreamSham/ZGloom-vita/issues/4](https://github.com/JetStreamSham/ZGloom-vita/issues/4)

[https://github.com/JetStreamSham/ZGloom-vita/issues/2](https://github.com/JetStreamSham/ZGloom-vita/issues/2) 

Along with some other bad bugs.

**Comment by Rinnegatamante** [comment]
@JetStreamSham When you think the official release is ready, please tag me and let me know so that i can close the issue and you can collect the bounty.

**Comment by JetStreamSham** [comment]
@Rinnegatamante  Official release is ready, you can close the issue.
