### ISSUE TITLE
Resident Evil 4 Vita Port

### ISSUE THREAD

**Issue by iStretchyDisc** [vita-nuova/bounties#47]
Whoever manages to fully port RE4 to the Vita and release it, I’ll give them $2000, no cap. I’m not a millionaire, but I have a pretty good job with a great salary (my field of work is IT) and am willing to pay $2k to anyone who’s able to accomplish this!

**Comment by Zyanbob** [comment]
where is it?

**Comment by Zyanbob** [comment]
because i would like to play it
