### ISSUE TITLE
[Android Port] Final Fantasy XV Pocket Edition for PS Vita [$100] 

### ISSUE THREAD

**Issue by derflash1** [vita-nuova/bounties#50]
Hi everybody, 

so i would give a 100 bucks for anybody who can make a clean port of this game, Maybe there'll be some other supporters who would like to join and add more to the bounty. 
I think this game should have been on the Vita anyway. I don't understand why they didn't release it. 
A port from the switch version could be done as well if that's even possible. 

Another 100 for a port of the steam or switch version of FF XII which would be awesome for the Vita as well. 

I am new and just discovered this site here and saw that you can make propositions for ports so if I am doing anything wrong please don't be angry with me. Cheers

**Comment by Rinnegatamante** [comment]
First of:
You need to actually open a bounty and put your money on it. No one is gonna work on something on request due to "words and promises".

Second of:
You can't port whatever comes in your mind (aka Steam/Switch stuffs).

**Comment by derflash1** [comment]
Okay, i will do that! I will have to register at bountysource right? But what you're saying is that my suggestions won't work?? Even the android version?

**Comment by Rinnegatamante** [comment]
Didn't take a look at the Android build which means i don't know if it's feasible.
