### ISSUE TITLE
[Plugin Creation] Use a SD2Vita card as a retail game [$120 awarded]

### ISSUE THREAD

**Issue by nad45** [vita-nuova/bounties#51]
As a PsVita collector, I'd like to make cartmods with their Vita games boxes for homebrews and only digitally released games.
Of course I could just make the boxes for my Collection but  it would be cooller if the game could actually work as a real retail one. 
For less than 20$ (SD2Vita +
empty vita game box + 4Go sd card + paper) , you can make your own "retail" game. 

I think some other people could be interested so I'm creating this Bounty

Here's few quickly made exemples of what could look like the art for some games I would like in my collection : 

![Jet Grind Vita](https://user-images.githubusercontent.com/42468542/117531546-3665a480-afe3-11eb-8cf0-53cef3190e0e.png)

![Bully](https://user-images.githubusercontent.com/42468542/117531981-82194d80-afe5-11eb-9c01-cd927202c890.png)

![Vice Vity](https://user-images.githubusercontent.com/42468542/117531608-8f353d00-afe3-11eb-9ccf-3cad8c0c3efc.png)

![Max Payne](https://user-images.githubusercontent.com/42468542/117531600-7dec3080-afe3-11eb-89df-5fb8be619819.png)

![Kick Fennick](https://user-images.githubusercontent.com/42468542/117531584-6a40ca00-afe3-11eb-8523-85687d472040.png)

![Sonic 2 Vita](https://user-images.githubusercontent.com/42468542/117531604-893f5c00-afe3-11eb-999f-89a99a3815a2.png)

**Comment by SKGleba** [comment]
plugin: https://github.com/SKGleba/VitaTools/tree/main/fakegc/build
source: https://github.com/SKGleba/VitaTools/tree/main/fakegc/source
instructions: https://github.com/SKGleba/VitaTools#fakegc

### Tested games/apps:
 - GTA Vice City
 - GTA San Andreas
 - Brain Splitter
 - molecularShell
 - OpenXCOM (requires the latest repatch)
 - Retro City Rampage DX (decrypted)
 - ScourgeBringer (decrypted)

**Comment by Rinnegatamante** [comment]
Closing the issue so that the bounty can be collected if backers accept the solution.

**Comment by K222222R** [comment]
Hi man, can u show the result through a video ? when u insert the card etc
thanks
