### ISSUE TITLE
[Android Port] Slay the Spire

### ISSUE THREAD

**Issue by ItsKipz** [vita-nuova/bounties#55]
Slay the Spire just got a port to Android, it is one of my favorite games and I think it would be a great fit for the Vita. The game uses something called "libGDX" that seems to be Java-based, I don't know if that makes this more or less difficult but that's the information I could find. 

Willing to set the bounty at $30 (although I don't know if there's something else I'm supposed to do to make that official before opening this issue) assuming the port is actually possible to create.

**Comment by Rinnegatamante** [comment]
To be honest, i wouldn't pu much hope in games running on those kind of engines rn.
