### ISSUE TITLE
[PC Port] Thief: the Dark Project & Thief: the Metal Age (willing to go $30+)

### ISSUE THREAD

**Issue by AvidzGamer** [vita-nuova/bounties#56]
Assuming we think this would be a possible port id be appreciative if someone could tell me how to set up the bounty :)
Id start at $30 but would be more than willing to increase it

I'm aware of the engine the being opensource called opendarkengine here: https://github.com  /volca02  /openDarkEngine

Its the engine that ran both thief's as well as systemshock as far as I know 
Im not sure if it would help but id be willing to provide copies of the games if needed

**Comment by Rinnegatamante** [comment]
OPDE is abandoned and unfinished afaik. This means those games can't be ported.
