### ISSUE TITLE
 [Android Port] ARK: Survival Evolved (willing to go $150)

### ISSUE THREAD

**Issue by prodigitalis** [vita-nuova/bounties#57]
Would love to see it, Will put money down.

What would it take to get the Android port to run on the Vita?

![image](https://user-images.githubusercontent.com/65131019/121325998-765ad700-c955-11eb-9d0b-2216a0233ef1.png)

**Comment by Rinnegatamante** [comment]
IT's simply too deamding for Vita.

**Comment by NathanGames21** [comment]
As awesome as it sounds Vita does not have anywhere near enough Ram
