### ISSUE TITLE
Captain Claw  (old pc platformer) ported on psvita

### ISSUE THREAD

**Issue by DonRamiro** [vita-nuova/bounties#59]
Pretty much what the title says. Captain Claw is an old platformer for the pc, which would look and play greatly on the psvita.

I dont know any technicalities about how easy or hard it would be to port but i think it would be awesome to play it on the go.

**Comment by Rinnegatamante** [comment]
There had been already an attempt to port it to Vita but the game crashes during first game loading. If one manages to fix that crash, the game would probably run just fine: https://github.com/rsn8887/OpenClaw/tree/vita

**Comment by DonRamiro** [comment]
Oh really? Damn! Thank you for this information! I tried my best to add a bounty to it, as i was not aware of the fact its been attempted allready but for some reason i couldnt go through with the process. I guess it was probably for the best. Here's hoping the crash gets resolved eventually. Thank you again, and feel free to delete this post.
