### ISSUE TITLE
Stepmania port

### ISSUE THREAD

**Issue by Rinnegatamante** [vita-nuova/bounties#6]
Since osu! is written in C# and would be high unlikely that someone would pick a source conversion bounty, i propose a Stepmania ( https://www.stepmania.com/ ) port for PSVITA.

An old version (3.9) of Stepmania is already available for PSP ( https://github.com/mafu9/PSPMania ) but a native port could benefit of higher res as well as touch input together with standard physical buttons support.

**Comment by devnoname120** [comment]
Some good contenders:
- https://github.com/McKay42/McOsu
- https://github.com/fmang/oshu
- https://github.com/zardoru/raindrop (very hard to port because of deps such as libRocket)

**Comment by kwt0728** [comment]
Is it possible to implement a background movie?
