### ISSUE TITLE
Port of Chiaki to Vita to enable ps5 remote play

### ISSUE THREAD

**Issue by AoifeHughes** [vita-nuova/bounties#60]
Hi,

There are open source PS5 remote play apps such as Chiaki which work well on other systems, such as the Nintendo Switch and PC. 

Is there any reason that this could not be also ported to the vita? 

I do not have experience in vita development, but I am an experienced software engineer and would also be happy to assist if someone would take the lead on this process. I will also still pay a bounty for this. If it turns out to be possible but a significantly harder job then I will also consider a higher bounty. 

The link to the aforementioned Chiaki git repo is below: 
https://git.sr.ht/~thestr4ng3r/chiaki

Also available is the Android APK (https://play.google.com/store/apps/details?id=com.metallic.chiaki) if there;s any reason that would be an easier porting process, though I would suspect not, given that the project is FOSS.

**Comment by Rinnegatamante** [comment]
Given how it even has a Switch port (which i guess runs on libnx), it shouldn't be too problematic to bring to Vita.
