### ISSUE TITLE
[Android Port to Vita] The World End With You - Solo Remix

### ISSUE THREAD

**Issue by Meonk69-Vita** [vita-nuova/bounties#62]
The World Ends with You is an action role-playing game co-developed by Square Enix and Jupiter for the Nintendo DS. Set in the modern-day Shibuya shopping district of Tokyo, The World Ends with You features a distinctive art style and urban fantasy elements inspired by Shibuya and its youth culture. Development was inspired by elements of Jupiter's previous handheld game, Kingdom Hearts: Chain of Memories. Later, an enhanced port by h.a.n.d. for mobile devices was released in 2012 under the title The World Ends with You: Solo Remix, while another enhanced port for the Nintendo Switch was released worldwide in 2018 under the title The World Ends with You: Final Remix.

SCREENSHOOT : 
![images jpeg-4](https://user-images.githubusercontent.com/87508776/125884477-3af64f58-6cdf-4148-b747-934d21274664.jpg)

![images jpeg-3](https://user-images.githubusercontent.com/87508776/125884523-5ad33718-09c4-4a37-ab24-4cdd11d4cd32.jpg)

![228496-the-world-ends-with-you-solo-remix-screenshot jpeg](https://user-images.githubusercontent.com/87508776/125884556-17eeedf8-bf10-4fe0-b6a9-6909a7f2c06f.jpg)

![228499-the-world-ends-with-you-solo-remix-screenshot jpeg](https://user-images.githubusercontent.com/87508776/125884003-f093f301-95cb-4c32-9c64-1d52d9c4168d.jpg)

GAMEPLAY :
https://youtu.be/--va1poaKDg

Its use ARMv7, so I think its possibble to ported to the PS Vita, would be awesome to play this game on PS Vita.

**Comment by irfanfadilah** [comment]
@Rinnegatamante why did you close most of the issues without any explanations? Even if it's not possible at least leave a simple comment.
