### ISSUE TITLE
[Android Port to Vita] NBA 2K13

### ISSUE THREAD

**Issue by kmika7e** [vita-nuova/bounties#63]
This was the first game of the franchise to come on Android, so I assume it's ARM based and therefore more likely to be ported than newer releases like 2K20. 

https://www.youtube.com/watch?v=q-1OdcCdPBI

As you can see in the gameplay it has way better visuals than PSP version of the game, actually it looks and plays closer to the PS3/360 versions. It would be an awesome addition, the Vita has a big gap in this genre since it never received a basketball game, 

Willing to set a bounty but first I'd like to hear if the game is actually portable from the devs. Thx!

**Comment by Rinnegatamante** [comment]
My general advice is to not set up bounties for those kind of games. No one has interest in proting those kind of games (at least for the people capable of porting Android titles) and in general no one would want to port a game that the next year would be meaningless.
