### ISSUE TITLE
Native Resolution output for PSTV [$145 awarded]

### ISSUE THREAD

**Issue by ScHlAuChii** [vita-nuova/bounties#7]
The Vita´s original resolution is 960x544.

PSTV outputs: 480p, 720p and 1080i.
This means the internal 960x544 resolution gets downscaled to 720x480, or upscaled to 1280x720 or 1920x1080. Unfortunately this type of scaling has some bad effects especially on pixel based games. It also adds a certain blurryness to the picture.

So what I´m asking for here is a modification that would allow the PSTV to directly output 960x544, or alternatively a 1280x720 picture that contains the 960x544 with black borders.

**Comment by ScHlAuChii** [comment]
xerpi already did some digging:
/CONFIG/DISPLAY/", "hdmi_out_scaling_ratio" the default number is 992647056
in the code this registry numbers is divided by 1.09e to 0.992647
some kind of fixed point number 0.992647056 might be a ratio like 4/3 = 1.33333

typedef struct SceDisplayFbDataCurFbInfo {
    SceUID pid;        // +0x50, +0x70
    void paddr;        // +0x54, +0x74
    unsigned int scaling;    // +0x58, +0x78
    float scaling_ratio;    // +0x5C, +0x7C
    unsigned int vp_x;    // +0x60, +0x80  16.16
    unsigned int vp_y;    // +0x64, +0x84  16.16
    unsigned int vp_width;    // +0x68, +0x88  16.16
    unsigned int vp_height;    // +0x6C, +0x8C  16.16
} SceDisplayFbDataCurFbInfo; / size = 0x20 /

typedef struct SceDisplayFbData {
    int lock;
    unsigned int enabled;
    int initialized;
    unsigned int vblankcount;
    unsigned int cb_event_uid;
    unsigned int unk14;
    unsigned int pulse_event_value;
    unsigned int dsi_bus;
    unsigned int plane_idx0;
    unsigned int plane_idx1;
    unsigned int vic; // VIC?
    unsigned int dst_width;
    unsigned int dst_height;
    unsigned int conv_flags; // enable conv?
    unsigned int dst_pixelformat; //0x00002000
    unsigned int pixel_size;
    float refresh_rate;
    unsigned int unk44;
    unsigned int brightness; // 0x10000 = max
    unsigned int invert_colors;
    SceDisplayFbDataCurFbInfo fb_set_info[2]; // +0x50
    unsigned int cb_uid;
    unsigned int brightness_control_value;
} SceDisplayFbData; / size = 0x98 */

**Comment by SpamU47** [comment]
Pretty interesting, I think I'll be supporting. I'm a bit afraid that this would be too niche to atract anybody. Also, I have doubts (sorry, I'm just a scene fan and have no knowledge at all) on how all different resolutions (as seen in VitaGrafix) would work in a 720p output. On the positive side, games that push an internal resolution of 1280x720 would be so sweet! Don't know if I'm mixing concepts, sorry guys.

@Rinnegatamante man, you're awesome. Thank you for your hard work. It's pure magic. I'll be helping in different bounties as they go (already contributed to the retroarch and PPSSPP ones -name Hidalgo-).

**Comment by ScHlAuChii** [comment]
![Test-Pattern](https://user-images.githubusercontent.com/12144392/64019397-55821280-cb2f-11e9-869e-fd282b78fdcb.png)

A resolution test image of alternating black and white lines in exactly 960x544.
If the output is scaled correctly there shouldnt be any patterns appearing!
Is the output scaled wrong, pattern appear that arent really there in the original image!

**Comment by cuevavirus** [comment]
https://github.com/cuevavirus/Sharpscale

Native 960x544 with black borders in 720p. Integer scaling up to 1920x1088 with 8 lines trimmed in 1080i.

Please use scalingtest.vpk to verify. This program draws directly to the framebuffer, whereas image viewers such as Vitashell or the photos app may introduce minor scaling or filtering effects.

**Comment by cuevavirus** [comment]
@ScHlAuChii If you are satisfied, please close this issue so I can claim the bounty. Otherwise please let me know what changes you require.

**Comment by ScHlAuChii** [comment]
@cuevavirus
Awesome that someone tackled this :)
I gave it a try and couldnt get it working (not sure what im doing wrong)
Installing the vpk resulted in Error 0xFFFFFFFF.

Update: Reason why plugin and VPK didnt work, was due to a corruption on the SD,
which seems to happen sometimes randomly with SD2Vita.

**Comment by ScHlAuChii** [comment]
Working solution provided by @cuevavirus - issue closed
Good work :)

Sharpscale can be found here:
https://github.com/cuevavirus/Sharpscale
