### ISSUE TITLE
PSSE Decryptor [$102 awarded]

### ISSUE THREAD

**Issue by NotSilica** [vita-nuova/bounties#73]
PSSE is the encryption scheme used by PlayStation Mobile games. It is simular to PFS where it encrypts all files in the game.

No one knows how it works... 
if you can make a decryption tool that does not require running the PS mobile runtime (eg, decrypting the files at run time does not count) it should just use the rif and files there.

It should work on both PSM Unity and PSM Normal games

Preferably this would be done on a computer rather than on the console, since on console you may as well do it with runtime,

Thanks

**Comment by NotSilica** [comment]
Claimed by KuromeSan https://github.com/KuromeSan/psse-decrypt

**Comment by tjmovie** [comment]
20 doller $
