### ISSUE TITLE
Vita as USB Keyboard [$10 awarded]

### ISSUE THREAD

**Issue by Civans** [vita-nuova/bounties#74]
I'd like to plug  my vita into my computer and use it as a keyboard.

Uhh.. How do I start a bounty and add money to it?

**Comment by Rinnegatamante** [comment]
Go on https://www.bountysource.com/ and click on left "Post Bouny" button and then follow the instructions.

**Comment by JetStreamSham** [comment]
did it https://www.bountysource.com/issues/102035644-vita-as-usb-keyboard
Oops wrong account

**Comment by MuddserAhmed** [comment]
Wireless would be even better ^_^

**Comment by mswlandi** [comment]
still testing, but tried my shot: https://github.com/mswlandi/vitakeyboard
should be working, but a little more testing is appreciated

**Comment by Rinnegatamante** [comment]
Closing issue so that bounty can be collected.

**Comment by Civans** [comment]
@mswlandi Thanks dude! Awarded you the bounty on bountysource.
