### ISSUE TITLE
Vita as software defined radio device[$50]

### ISSUE THREAD

**Issue by redsuit1** [vita-nuova/bounties#78]
I would like to try to make my vita able to listen to the Ham bands on the internet, I can accept the use of peripheries as I know that the vita was obviously not designed to do this however I think it'd be possible to create a powerful little internet relayed ham radio on this device. I propose that this would be possible to do with an RTL SDR dongle such as a nooelec or equivalent as referenced by this video: https://www.youtube.com/watch?v=L7RLJt4vZ_g

Ideally we might be able to utilize this device to form a meshnet but that may be wishful thinking as I doubt RF freqs could be accessed without heavy modification of the console which is not my goal yet. I'm up for discussion on this and would love to hear from others what they think about this project, price set is just to catch your eye unless some wiz comes along and does it, in which case I'll pay that wiz what I listed this bounty at, however as progress or interest is underway I will value the bounty more appropriately based on what I think the work is worth.

**Comment by Rinnegatamante** [comment]
If a bounty is not properly opened on the issue. The issue will be closed in 2 weeks.
