### ISSUE TITLE
[PC Port] Severance: Blade the edge of darkness  [$30] 

### ISSUE THREAD

**Issue by Operandix** [vita-nuova/bounties#79]
Is it possible to port this PC game to Vita? (launched: 2001)

![imagen](https://user-images.githubusercontent.com/60945594/142514633-1c6246e1-a9ee-42c7-83d4-25e86c479e35.png)

https://www.youtube.com/watch?v=PiYcRYB7ThE 

willing to pay the bounty for it. Thanks!

**Comment by MuddserAhmed** [comment]
https://github.com/smartblade/BldMystery
