### ISSUE TITLE
[PC Port] Serious Sam First/Second Encounter (Classic PC versions) [100$]

### ISSUE THREAD

**Issue by rkudrin** [vita-nuova/bounties#80]
Greetings. Is it possible to port the classic Serious Sam First/Second Encounter?
They worked well at a Pentium 233 megahertz. With the optimization and flexibility of graphics settings, these games are doing well.

PS: After GTA Vice City and Max Payne, there was hope that my dream could come true and Serious Sam would be available on PS Vita :)
![ss1](https://user-images.githubusercontent.com/87517618/143193365-13201fd2-0c42-400a-a921-8a38ed12776d.jpg)

**Comment by Mullpacha13** [comment]
That would be insane!

**Comment by Rinnegatamante** [comment]
No bounty attached to this Issue. Closing it.

**Comment by rkudrin** [comment]
@Rinnegatamante I apologize. Here is the link to bounty. If I have to redo it, let me know. Please, reopen issue.

https://app.bountysource.com/issues/103499939-pc-port-serious-sam-first-second-encounter-classic-pc-versions-100

**Comment by Rinnegatamante** [comment]
There's no bounty on the issue. Bounty = Money have been already dropped in on Bountysource.
