### ISSUE TITLE
[Android Port] Droidfish Chess 

### ISSUE THREAD

**Issue by BlackSheepBoy69** [vita-nuova/bounties#86]
https://app.bountysource.com/issues/105685020-android-port-droidfish-120

"DroidFish is a feature-rich graphical chess user interface, combined with the very strong Stockfish chess engine."

Their Github: https://github.com/peterosterlund2/droidfish

My favorite chess game, port for vita.

![main](https://user-images.githubusercontent.com/97395721/156121188-17b5fa0d-59ec-4770-b9f6-800270bde817.png)

Details related to the bounty:

Ensure the save/load feature works.

Remap android menu button to vita start button

Remap android back button to vita triangle button. Please don't let it suspend the app when pressed outside a menu (more of a preference than a requirement).

Why Droidfish is the best:

Edit the board to give each player 8 queens and continue as if nothing ever happened. You could
even use hints or repeatedly switch sides to have the computer fight itself.

Is the cpu taking too long (like it probably will on vita)? There's time controls for total AND
   incremental time for the computer. You can also have the cpu "think" while it's your turn.

Too hard? In addition to the "Stockfish" cpu (pro), there's also a "CuckooChess" cpu (noob) that lets you set the difficulty quite low to the point that "even beginners have a reasonable chance to beat it".

Beautiful clean default graphics.

Want to see what would have happened if the computer chose a bad move?
   Press the "M" icon and switch sides, then go back 1 turn.
   Make the computer choose a bad move.
   Press the "M" icon and switch sides, then go back 1 turn (to undo computer's move for your side if applicable).
   Continue as if nothing ever happened.

Lightbulb button lets you quickly show/hide the computer thinking WHILE IT'S THINKING. Very cool.

Save/load the game to a file.

It gives you suggestions on the first few moves (you can disable this in settings).

![pic2](https://user-images.githubusercontent.com/97395721/156121214-0daf2f7b-5dfd-4ec4-8cca-a2fa7fd25cae.png)

**Comment by Rinnegatamante** [comment]
This game looks like it has quite intensive Java usage. As such, porting it is basically impossible unless someone extremely dedicated decides to take it (it would mean having to rewrite the whole Java interface through wrappers, it's an insane job that likely no one will ever take in consideration.
I suggest you to withdraw the bounty or redirect it to something else more plausible.

**Comment by BlackSheepBoy69** [comment]
Wrapper is kind of vague, is it as simple as recoding it all in a vita compatible language like C++/lua? Is there a special "wrapper" code for android-to-vita ports? I am not familiar with how android-to-vita is done but I would be interested to know.

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/ff4_vita/blob/ff4/loader/bridge.c

Stuffs like these should be done for the whole UI, the workload is huge.

**Comment by BlackSheepBoy69** [comment]
Serious question, how much $$$ would it take for someone to seriously consider porting it?

**Comment by BlackSheepBoy69** [comment]
After inspecting it, I can see this is a REALLY big job, ~~I will probably have something SIMILAR to droidfish made soon with more realistic expectations from a small coder team I know.~~ Aside, what are some android ports ( other than the ones listed as "worked on" on android.rinnegatamante ) you'd be interested in doing if there was a bounty on them? I'd definitely be interested to know and will re-route this bounty and/or put a larger amount towards it if I'm interested, please reply or PM me. Especially if you were interested in porting that call of duty zombies I have on my phone which you list as a candidate.

**Comment by Sergei-Udris** [comment]
- wanted to take this bounty puck - but not going to
- porting earlier programs including games is a noble quest - like TheMexicanRunner being keeper of all-NES
- but should be generic, for desktop and mobile - not just for a specific new platform
- should be like China Study and Game Changers - whole foods plant based vegan  - written in clojure and released as uber .jar for Linux Win Mac Android
- no cloud binary compilation insanity - it's like Fiona Oakes running across Sahara carrying the huge house-bag on her
- why?! - we should move light between houses - users have JVM installed and programmers can deliver light standalone .jars of meaning
- too few meaningful games are open source - everything is ugly Lord-Business-proprietary and hidden- but like with StarCraft Broodwar: Remastered should be ports of Loved-Game-That-Used-to-RUn-Only-On-This: reJesused - like Starlord in End Game says, which master do i serve? what am i supposed to say, Jesus?! - but thanks, Linus, anyway for caesaring it up and making master branch the default

that said
 - these - github.com/vita-nuova/bounties - kind of bounties are more merciful - which require to program re-program a program as a whole
 - as opposed to the most github's label:bounty litter - where Alain-Caesar-Delon-ave-moi! programmers hypocritically ask to help them - doctor, help me but only don't change my animal-based diet of imperative languages and style-guides and no processes-queues - the very reason program does not work as expected in the first place - and dragging more work-force and pills is the pinnacle of self-lies

i will seek bounties where goal is to deliver whole program
- either reJesus existing program who has finite identity but does not work as expected or only on this-or-that-OS
- or a will from users - non-programmers - saying what program should be with a finite feature list - again delivered as .jar of beskar parens ( ) for Linux Mac Win Android iOS

:Lee-Camp 
- you don't have to quit meat, alright? just decrease he amount you eat a little each moth until it's 0
- or you can do what i do - i only eat meat that's hard to get - endangered species, that's it - platypus pygmy hippos and baby echidnas

**Comment by BlackSheepBoy69** [comment]
what

**Comment by xlokk73** [comment]
I don't know if it is relevant, but there is an iOS version which relies on C++ rather than java. https://github.com/lamxing/stockfishchess-ios

**Comment by BlackSheepBoy69** [comment]
I never tried that one but there doesn't seem to be much documentation on that which is a shame. From a google search I'm not sure that it has the ability to show what it's thinking while it's thinking. I may keep it in mind. ~~If no one else takes the bounty I was planned to have small code team work on it with me in November/December and have a working prototype by Christmas (hopefully). There's not much experience with C++ but we'll try, it seems like we'll be going down the C++ route anyway and this app you sent me is in C++ so we might use it as a base if nothing can be found with better documentation~~

**Comment by BlackSheepBoy69** [comment]
@Rinnegatamante @rubberduckydrip
My friend got deported so there will be no more progress from me on making it myself. I will probably redirect this bounty to something that seems more like it has a chance of actually being ported if no one else is interested in either porting this or porting Java which would work too but I don't think there is that much interest in Java overall.

**Comment by BlackSheepBoy69** [comment]
> This game looks like it has quite intensive Java usage. As such, porting it is basically impossible unless someone extremely dedicated decides to take it (it would mean having to rewrite the whole Java interface through wrappers, it's an insane job that likely no one will ever take in consideration. I suggest you to withdraw the bounty or redirect it to something else more plausible.

@Rinnegatamante How to redirect a bounty? Do I just email their bountysource zendesk support email about it?

**Comment by BlackSheepBoy69** [comment]
I emailed their support about transferring it to the zelda port: https://github.com/vita-nuova/bounties/issues/118

If the Zelda port gets done before anything happens, claim this bounty with it.

**Comment by BlackSheepBoy69** [comment]
amount has been refunded to bountysource account... I put it on the zelda bounty, just waiting on processing.
