### ISSUE TITLE
[Android Port] Galaxy on Fire 2 HD [$245]

### ISSUE THREAD

**Issue by CatoTheYounger97** [vita-nuova/bounties#94]
Galaxy on Fire 2 is a space sim, with exploration, trading, combat and freelancing.  The base game is free to play, with paid premium story expansions. It is a known candidate port for the PS VITA:
https://github.com/Rinnegatamante/Android2Vita-Candidate-Ports-List/issues/93

This bounty is for porting the base game + premium DLC: 
- Galaxy on Fire 2 HD Base game 
- Valkyrie Expansion 
- Supernova Expansion 
- Kaamo Club Station 

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/82458228/180338220-ce2a8b15-f143-4f86-ae9d-3de4f934ad40.jpg)
![unnamed](https://user-images.githubusercontent.com/82458228/180338123-6bef58c8-b97c-4cbc-a485-0ecbc706e60b.jpg)
![unnamed](https://user-images.githubusercontent.com/82458228/180338154-c00d81d4-ab2e-4883-b5cf-fc1611ee2e66.jpg)

**Links and Videos**
- Google Play Store: https://play.google.com/store/apps/details?id=net.fishlabs.gof2hdallandroid2012&hl=en_GB&gl=US
- Gameplay: https://www.youtube.com/watch?v=IlWysAl5PwI

**Additional Information**
- This game uses FMOD.

Bounty page: https://app.bountysource.com/issues/110045817-android-port-galaxy-on-fire-2-hd

**Comment by CatoTheYounger97** [comment]
Alternate Game Version :
- There is an earlier armv6 version of this game (Galaxy on Fire 2 v1.0.4.2)
- This verion used OpenAL instead of FMOD
- This version does not contain the DLC
- This version has lower quality assets (textures + models)

**Comment by NDRWhun** [comment]
> 

Or 1.0.4.9 with valkyrie expansion (Xperia Play Version too).
Same as above.

**Comment by CatoTheYounger97** [comment]
The xplay version with valkyrie expansion uses FMOD and so has the same sound problem as the HD version. Therefore, only the version I mentioned above is worth looking into as an alternative (v1.0.4.2).

**Comment by v-atamanenko** [comment]
Solved with https://github.com/v-atamanenko/gof2-vita/
Reached a mutual agreement with backers regarding the HD version: they will receive a build of the HD edition (with all DLCs) that, unfortunately, has no sound, but I will continue trying to tackle FMOD in the future
