### ISSUE TITLE
F1 2016 Android port to PS Vita

### ISSUE THREAD

**Issue by KaleBellota** [vita-nuova/bounties#96]
Hello there is a F1 2016 for Android, I would like to know if is possible port that game to PS Vita. If yes, then we can open a bounty. Thank you, have a nice day.

**Comment by Rinnegatamante** [comment]
The game, from a rapid look, looks portable (it's ARMv7 and uses GLES2) however it may be too resource hungry for Vita (we can't really know until someone attempts to port it).

If you want to start a bounty for it, you can. At worst, if someone attempts to port it and realizes that is not portable, you can still ask Bountysource to give you back the money or you can re-direct the money to another bounty.
