### ISSUE TITLE
Residenr Evil Degeneration and RE4 Android Port

### ISSUE THREAD

**Issue by Veget4** [vita-nuova/bounties#97]
Hello. It is possible Resident Evil 4 Mobile Edition port to PS Vita.

I see the game in a previous list of possible games, but i think not only this game would be possible.

In 2008 Resident Evil Degeneration comes to iPhone, and use the same engine. Is possible too ?
Or the N Gage version of Degeneration.

**Comment by Rinnegatamante** [comment]
Do you know what a bounty is?

**Comment by Veget4** [comment]
Yes. I forget that part, sorry. 25$ for only Resident Evil 4 Mobile ?
